name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: tj-actions/changed-files@v42
      id: changed-files
      with:
        dir_names: true
        dir_names_exclude_current_dir: false
        dir_names_include_files: src/*
        files: src/**
        dir_names_max_depth: 2
    - name: List all changed folders
      id: changed-folders
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        dir_changed="["
        for file in ${ALL_CHANGED_FILES}; do
          dir_changed+="'$(echo $file | sed -E 's/src\///')',"
        done
        dir_changed+="]"
        echo "GITHUB_DIR_CHANGED=${dir_changed}" >> "$GITHUB_OUTPUT"
    outputs:
      dir-changed: ${{ steps.changed-folders.outputs.GITHUB_DIR_CHANGED }}

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.dir-changed) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.0
      prefix: ${{ matrix.app }}-
      log-path: ${{ matrix.app }}/
      release-branch: main
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          # list of Docker images to use as base name for tags
        images: |
          docker.io/skandabhatt/${{ matrix.app }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=${{ steps.version.outputs.version }}
          type=ref,event=branch
          type=ref,event=pr
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/bake-action@v4
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: ${{ matrix.app }}
        push: true
        no-cache: true
      
